"""Build algorithm-by-environment residual audit tables."""

from __future__ import annotations

import csv
from pathlib import Path

import numpy as np

from certgap.analysis.audit import collect_audit_rows


def _fmt(value: float) -> str:
    return "--" if not np.isfinite(value) else f"{value:.2f}"


def main() -> None:
    rows = collect_audit_rows()
    out_dir = Path("figures/out")
    out_dir.mkdir(parents=True, exist_ok=True)

    csv_path = out_dir / "table_residual_audit.csv"
    if rows:
        with csv_path.open("w", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)
    else:
        csv_path.write_text("algorithm,env\n")

    tex_path = out_dir / "table_residual_audit.tex"
    lines = [
        r"% Generated by scripts/build_audit_table.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"Algorithm & Env & $n$ & $-\epsilon_u$ & $-\epsilon_{u,\mathrm{mse}}$ & $-\hat\Delta$ \\",
        r"\midrule",
    ]
    for row in rows:
        env_short = row["env"].split("-")[0]
        lines.append(
            f"{row['algorithm']} & {env_short} & {row['n_runs']} "
            f"& {_fmt(row['auroc_neg_eps_u'])} "
            f"& {_fmt(row['auroc_neg_eps_u_mse'])} "
            f"& {_fmt(row['auroc_neg_delta_hat'])} \\\\"
        )
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{\textbf{Bellman residual audit across algorithms.} Median per-seed AUROC for predicting beneficial return changes. Values near 0.5 indicate chance-level association between the diagnostic and realized policy improvement.}",
        r"\label{tab:residual-audit}",
        r"\end{table}",
    ]
    tex_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {csv_path}")
    print(f"wrote {tex_path}")


if __name__ == "__main__":
    main()
